### PR TITLE
Automatically download FIA PDFs

### PR DESCRIPTION
**Pull request by theOehrly**
Here my implementation for automatically downloading PDFs, finally.

I'll give you some example code.

```python
from fia_download import FIADocumentsInterface


# set path to an existing directory
fia = FIADocumentsInterface(backend_path="../data")


# example: print the name of the latest event and get the entry list as well
# as the lap chart for the race

events = fia.list_events(2024)

print("Most recent event is:", events[0])

# get a decision document, don't specify a session
doc_entry_list = fia.get("Entry List", 2024, events[0])

print(f"Entry List: {doc_entry_list.name} "
      f"- {doc_entry_list.last_modified}, "
      f"updated: {doc_entry_list.was_updated}")

# get a timing document, specify a session
doc_race_classification = fia.get("Lap Chart", 2024, events[0], 'race')

print(f"Entry List: {doc_race_classification.name} "
      f"- {doc_race_classification.last_modified}, "
      f"updated: {doc_race_classification.was_updated}")

# The documents are already downloaded and the PDF content is stored as a
# bytes object in the `content` attribute of the Document object. You can
# directly use the document content to extract information from the PDFs (or
# save it to a file as shown in the next example).

with open(doc_entry_list.name + ".pdf", "wb") as f:
    f.write(doc_entry_list.content)

# mainly for debugging purposes, you can also open the document in the default
# web browser
doc_entry_list.open_in_browser()
```

This will output something like

```console
Most recent event is: São Paulo Grand Prix
Entry List: Entry List - 2024-11-01 12:33:02, updated: False
Entry List: Lap Chart - 2024-11-03 18:57:18, updated: False
```

The API is not very complicated. Mainly, it consists of

- class ``FIADocumentsInterface``
  - function ``.check_if_updated``
  - function ``.get``
  - function ``.get_if_updated``
  - function ``.list_events``
  
- class ``Document``

Everything is mostly documented in the code. So it shouldn't be too difficult to test it out.

A bit of explanation on the detection if a document was updated. The code keeps a JSON file in the specified backend directory. This file contains metadata about all documents that have ever been downloaded. 
Whenever a document is loaded with ``.get`` or ``.get_if_updated``, this metadata is updated. Therefore, if a document is marked as updated, the next time you load it, it will not be marked as updated anymore. Except of course when it was modified on the server.

We talked about running the ingest process in Github Actions. My idea here is to use the cache action in the workflow to store the JSON index between runs. If the ingest workflow fails, the cache will not be saved (default behaviour, if I remeber correctly). In that case, the index changes are not stored, so when the workflow is re-run, it will still consider the same documents as updated until it succeeds.

### CODE REVIEW

**Comment by theOehrly** [comment]
@harningle regarding that warning that you would like to receive for provisional documents, how do you want to get that warning? Some ``.is_provisional`` property on the returned document object? A Python warning (``warnings.warn(....)``), probably a UserWarning then? Both? Or did you have something else in mind?

**Comment by harningle** [comment]
> @harningle regarding that warning that you would like to receive for provisional documents, how do you want to get that warning? Some `.is_provisional` property on the returned document object? A Python warning (`warnings.warn(....)`), probably a UserWarning then? Both? Or did you have something else in mind?

I'd like both. When we download and parse the PDF, we can check `.is_provisional` and then decide what to do. UserWarning can be very helpful if we run it interactively

**Comment by harningle** [comment]
sorry I mis- force pushed and overwrited the commit history. Hope that doesn't affect your work too much (your downloading scripts will be put in a separate repo anyways, as we discussed in the last meeting?)

**Comment by theOehrly** [comment]
No problem, we'll figure that out. I had already rebased this onto the 'combine-scripts' branch for development. I'll open a new PR at some point.

**Pull request closed without merging**
